- src/pages/portfollo/_config/columns/columns.type.ts
- src/pages/portfollo/_config/columns/facetedFilters.tsx
- src/pages/portfollo/_config/columns/index.tsx
- src/pages/portfollo/_config/query/index.ts
- src/pages/portfollo/_config/query/queryKeys.ts
- src/pages/portfollo/_config/schema/index.ts
- src/pages/portfollo/_config/types/index.tsx
- src/pages/portfollo/authorities/add-or-update.tsx
- src/pages/portfollo/authorities/index.tsx
- src/pages/portfollo/certificate-course-fee/add-or-update.tsx
- src/pages/portfollo/certificate-course-fee/index.tsx
- src/pages/portfollo/department/add-or-update.tsx
- src/pages/portfollo/department/index.tsx
- src/pages/portfollo/faculty/add-or-update.tsx
- src/pages/portfollo/faculty/index.tsx
- src/pages/portfollo/program/add-or-update.tsx
- src/pages/portfollo/program/index.tsx
- src/pages/portfollo/tuttion-fee/add-or-update.tsx
- src/pages/portfollo/tuttion-fee/index.tsx
Introduce a portfolio section that includes query keys, schemas, and updates to various components for managing designations and departments. This enhances the application's functionality and structure.
> Add portfolio section with query keys, schemas, and components updates

- src/pages/hr/department/index.tsx
- src/pages/portfollo/_config/schema/index.ts
- src/pages/portfollo/_config/types/index.tsx
- src/pages/portfollo/authorities/add-or-update.tsx
- src/pages/portfollo/certificate-course-fee/add-or-update.tsx
- src/pages/portfollo/department/add-or-update.tsx
- src/pages/portfollo/tuittion-fee/add-or-update.tsx
- src/pages/portfollo/tuittion-fee/index.tsx
- src/types/index.ts
Enhance type safety and null handling in department and tuition fee components by updating type definitions and ensuring proper data handling.
> Improve type handling and null exports for department and tuition fee components

- src/pages/portfolio/_config/columns/columns.type.ts
- src/pages/portfolio/_config/columns/index.tsx
- src/utils/formdata.ts
> fixed portfolio info update

- package-lock.json
- package.json
- src/components/core/form/index.tsx
- src/components/core/form/rich-text-editor/index.tsx
- src/components/core/modal/index.ts
- src/components/core/modal/rich-text-modal.tsx
- src/components/core/modal/types.ts
- src/components/ui/rich-text-viewer.tsx
- src/index.css
- src/pages/portfolio/_config/columns/index.tsx
- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/department-teacher/add-or-update.tsx
> added rich-text-editor and department head field to department teachers

- eslint.config.js
- src/pages/portfolio/_config/columns/columns.type.ts
- src/pages/portfolio/_config/columns/index.tsx
- src/pages/portfolio/_config/query/index.ts
- src/pages/portfolio/_config/query/queryKeys.ts
- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/_config/types/index.tsx
- src/pages/portfolio/offers/add-or-update.tsx
- src/pages/portfolio/offers/index.tsx
- src/routes/private/portfollo.tsx
> ci: :sparkles: Added Offers page

- src/components/ui/calendar.tsx
> fixed build errors

- src/types/enum.ts
Introduce a new enum value for Notices in the PORTFOLIO_PAGE_NAME to enhance the portfolio page functionality.
> Add Notices enum to PORTFOLIO_PAGE_NAME

- src/pages/portfolio/info/add-or-update.tsx
- src/pages/portfolio/info/index.tsx
Rename the Designation component to Info and update the URL for the delete item functionality. Clean up imports in the add-or-update component.
> Refactor Designation component to Info and update delete URL

- src/pages/portfolio/admission/_config/columns/columns.type.ts
- src/pages/portfolio/admission/_config/schema/index.ts
- src/pages/portfolio/admission/certificate-course-fee/add-or-update.tsx
- src/pages/portfolio/admission/certificate-course-fee/index.tsx
- src/pages/portfolio/routine/index.tsx
Update the delete item functionality URL in the Designation component and refactor program identifiers for consistency across related components.
> Fix delete item URL and refactor program identifiers in Designation component

- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/_config/types/index.tsx
- src/pages/portfolio/admission/_config/columns/columns.type.ts
- src/pages/portfolio/admission/_config/columns/index.tsx
- src/pages/portfolio/admission/_config/schema/index.ts
- src/pages/portfolio/admission/tuition-fee/add-or-update.tsx
- src/pages/portfolio/admission/tuition-fee/index.tsx
- src/pages/portfolio/offers/add-or-update.tsx
- src/pages/portfolio/offers/index.tsx
Introduce file upload functionality for offers, enhancing the form to accept file inputs and updating related components accordingly.
> Add file upload support to offers

- src/pages/portfolio/_config/columns/index.tsx
Introduce a new column in the offers table that displays a file preview, enhancing the user interface and functionality.
> Add file column with preview functionality to offers table

- src/components/others/link.tsx
- src/pages/inquiry/_config/schema/index.ts
- src/pages/portfolio/_config/columns/columns.type.ts
- src/pages/portfolio/_config/columns/index.tsx
- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/boardOfTrustees/utils.ts
- src/pages/portfolio/department/add-or-update.tsx
- src/pages/portfolio/routine/index.tsx
- src/routes/private/portfollo.tsx
Improve the LinkWithRedirect component to conditionally use a base URL and update various schemas to include a new page_link field. This change enhances navigation and data structure consistency across the application.
> Enhance LinkWithRedirect component and update schemas for page_link

- src/pages/hr/_config/schema/index.ts
- src/pages/portfolio/useful-links/_config/columns/index.tsx
Make the phone field nullable and introduce an is_global column in the news table for enhanced data management.
> Update phone field and add is_global column to news table

- src/pages/procurement/category/add-or-update.tsx
- src/pages/procurement/category/config/columns/columns.type.ts
- src/pages/procurement/category/config/columns/facetedFilters.tsx
- src/pages/procurement/category/config/columns/index.tsx
- src/pages/procurement/category/config/query/index.ts
- src/pages/procurement/category/config/query/queryKeys.ts
- src/pages/procurement/category/config/schema/index.ts
- src/pages/procurement/category/config/types/index.tsx
- src/pages/procurement/category/index.tsx
- src/pages/procurement/category/utils.ts
- src/routes/private/index.tsx
- src/routes/private/procurement.tsx
Establish a new procurement section with components for adding and updating visitor inquiries, including form handling and routing. Implement necessary schemas, queries, and table configurations.
> Initial setup for procurement section

- src/pages/portfolio/teacher/add-or-update.tsx
- src/pages/portfolio/teacher/index.tsx
Correct the API URLs for post, update, and delete operations on the teachers page to ensure proper functionality.
> Fix API URL for teachers page operations

- src/pages/portfolio/useful-links/news/entry.tsx
- src/types/index.ts
Resolve an issue with the news entry image and update the title and field name for better clarity.
> Fix news entry image bug and update field names

- src/pages/portfolio/routine/add-or-update.tsx
- src/pages/portfolio/useful-links/club/add-or-update.tsx
- src/pages/portfolio/useful-links/club/index.tsx
Correct the API URLs used for updating and posting club and routine data to ensure proper functionality.
> Fix API URLs for club and routine updates

- src/pages/hr/_config/schema/index.ts
- src/pages/portfolio/admission/_config/columns/index.tsx
- src/pages/portfolio/useful-links/job-circular/add-or-update.tsx
- src/pages/portfolio/useful-links/job-circular/index.tsx
Enhance image validation to ensure a file is uploaded and update URLs for job circular operations to be more consistent.
> Update image validation and adjust job circular URLs

- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/admission/_config/schema/index.ts
- src/pages/portfolio/admission/online-form/add-or-update/index.tsx
Corrected the schema for office entries and tuition fees to enforce required fields and minimum values. Updated the navigation redirect after form submission to the appropriate URL.
> Fix schema and redirect issues in admission forms

- package-lock.json
- package.json
- src/components/core/data-table/_views/column-avatar.tsx
- src/components/core/modal/content-modal.tsx
- src/components/core/modal/index.ts
- src/components/core/modal/types.ts
- src/components/ui/avatar.tsx
- src/pages/hr/_config/columns/index.tsx
- src/pages/portfolio/_config/columns/index.tsx
- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/teacher/add-or-update.tsx
> added avatar

- src/pages/portfolio/department/utils.ts
- src/routes/private/portfollo.tsx
Introduce a new category 'None' and an action for 'Extra Curricular Club' in the portfolio management system.
> Add new categories and actions for portfolio

- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/routine/add-or-update.tsx
- src/types/enum.ts
Introduce a type conditional to show the programs field in the entry form only when the selected type is not 'notices'. This change enhances form validation and user experience.
> Add conditional display for programs field in entry form

- src/components/core/form/date-picker.tsx
- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/teacher/add-or-update.tsx
> fix: :bug: fixed calendar issue

- src/pages/portfolio/_config/schema/index.ts
> fixed build error

- src/components/core/form/form-dynamic-fields/_components/default.tsx
- src/components/core/form/form-dynamic-fields/types.ts
- src/components/core/form/react-select.tsx
- src/components/core/form/types.ts
- src/pages/procurement/item-work-order/config/schema/index.ts
- src/pages/procurement/item-work-order/entry.tsx
- src/pages/procurement/item-work-order/useGenerateFieldDefs.tsx
Enhance the item work order entry page by adding onChange handlers, modifying validation rules, and streamlining the submission process. This update improves the user experience by allowing dynamic field management and better data handling.
> Update item work order entry page functionality

- src/pages/procurement/capital/config/types/index.tsx
- src/pages/procurement/service/config/types/index.tsx
Remove unused import and clean up the item add/update interface definition.
> Fix bug in item add/update interface

- src/components/core/form/date-picker.tsx
- src/components/core/form/types.ts
- src/components/ui/calendar.tsx
- src/pages/procurement/service/entry.tsx
> fixed date picker issue

- src/components/ui/date-time.tsx
- src/pages/portfolio/teacher/add-or-update/card/index.tsx
- src/pages/procurement/form/add-or-update.tsx
- src/pages/procurement/form/config/columns/columns.type.ts
- src/pages/procurement/form/config/columns/facetedFilters.tsx
- src/pages/procurement/form/config/columns/index.tsx
- src/pages/procurement/form/config/query/index.ts
- src/pages/procurement/form/config/query/queryKeys.ts
- src/pages/procurement/form/config/schema/index.ts
- src/pages/procurement/form/config/types/index.tsx
- src/pages/procurement/form/index.tsx
- src/pages/procurement/item-work-order/config/columns/index.tsx
- src/pages/procurement/item-work-order/config/schema/index.ts
- src/pages/procurement/item-work-order/entry.tsx
- src/pages/procurement/item-work-order/useGenerateFieldDefs.tsx
- src/pages/procurement/item-work-order/utils.ts
- src/pages/procurement/vendor/add-or-update.tsx
- src/pages/procurement/vendor/config/columns/index.tsx
- src/pages/procurement/vendor/config/schema/index.ts
- src/routes/private/procurement.tsx
Enhance the procurement section by adding new fields to vendor and item work order entry forms, implementing CRUD functionality for forms, and cleaning up unused imports.
> Add vendor and item work order forms with CRUD functionality

- src/components/buttons/field-action.tsx
- src/components/core/data-table/_components/cell-action.tsx
- src/components/core/form/date-picker.tsx
- src/components/core/form/types.ts
- src/pages/portfolio/teacher/add-or-update/card/index.tsx
- src/pages/procurement/internal-cost-center/utils.ts
- src/pages/procurement/item/config/columns/index.tsx
- src/pages/procurement/item/config/schema/index.ts
- src/pages/procurement/item/entry.tsx
- src/pages/procurement/requisition/config/columns/index.tsx
- src/pages/procurement/requisition/config/query/index.ts
- src/pages/procurement/requisition/config/schema/index.ts
- src/pages/procurement/requisition/entry.tsx
- src/pages/procurement/requisition/index.tsx
- src/pages/procurement/requisition/provided.tsx
- src/pages/procurement/requisition/useGenerateFieldDefs.tsx
- src/routes/private/procurement.tsx
Improve requisition forms and schemas to support new item requisition logic, access control, and additional fields for item status. Introduce a new entry page for requisitions.
> Enhance Requisition functionality and entry page

- src/components/core/data-table/_components/toolbar.tsx
- src/context/TableContext.tsx
- src/pages/procurement/report/config/columns/columns.type.ts
- src/pages/procurement/report/config/columns/facetedFilters.tsx
- src/pages/procurement/report/config/columns/index.tsx
- src/pages/procurement/report/config/query/index.ts
- src/pages/procurement/report/config/query/queryKeys.ts
- src/pages/procurement/report/item/index.tsx
- src/routes/private/procurement.tsx
- src/types/index.ts
Introduce a new report item feature with integrated toolbar components and default date range settings. This update enhances the reporting capabilities by allowing users to filter data based on specified date ranges.
> Implement report item functionality with date range filtering and toolbar integration

- src/pages/portfolio/department/utils.ts
- src/routes/private/portfollo.tsx
- src/routes/private/utils.ts
Introduce additional subjects including Physics, Mathematics, and Chemistry to enhance the DepartmentAccess and short_names for better coverage. Adjustments made to the portfolio routes for consistency.
> Add new subjects to DepartmentAccess and short_names for completeness

- src/pages/portfolio/_config/schema/index.ts
- src/pages/portfolio/teacher/add-or-update/index.tsx
- src/pages/portfolio/teacher/add-or-update/types.ts
- src/pages/portfolio/useful-links/_config/schema/index.ts
- src/pages/portfolio/useful-links/news/entry.tsx
Introduce a status field to the ICard interface and related schemas for consistency. Improve validation for ROUTINE_SCHEMA to provide clearer error messaging when required fields are missing.
> Add status field to ICard and enhance ROUTINE_SCHEMA validation

- src/components/ui/table.tsx
> added sticky table header and footer

- src/components/core/modal/details.tsx
- src/components/core/modal/index.ts
- src/components/core/modal/types.ts
- src/pages/procurement/item/config/columns/columns.type.ts
- src/pages/procurement/item/config/columns/index.tsx
- src/pages/procurement/item/config/query/index.ts
- src/pages/procurement/item/config/query/queryKeys.ts
- src/pages/procurement/item/details.tsx
- src/pages/procurement/item/index.tsx
- src/pages/procurement/log/config/columns/columns.type.ts
- src/pages/procurement/log/config/columns/index.tsx
- src/pages/procurement/log/config/query/index.ts
- src/pages/procurement/log/config/query/queryKeys.ts
- src/pages/procurement/log/config/schema/index.ts
- src/pages/procurement/log/config/types/index.tsx
- src/pages/procurement/log/index.tsx
- src/pages/procurement/log/item-requisition/add-or-update.tsx
- src/pages/procurement/log/item-requisition/index.tsx
- src/pages/procurement/log/item-work-order-entry/add-or-update.tsx
- src/pages/procurement/log/item-work-order-entry/index.tsx
- src/pages/procurement/vendor/config/columns/columns.type.ts
- src/pages/procurement/vendor/config/columns/index.tsx
- src/pages/procurement/vendor/config/query/index.ts
- src/pages/procurement/vendor/config/query/queryKeys.ts
- src/pages/procurement/vendor/details.tsx
Introduce a DetailsModal component to enhance the user experience by displaying detailed information for item vendors and work orders. Update relevant components and queries to support this new functionality, including the addition of new types and refactoring existing components for better integration.
> Add DetailsModal for item vendors and work orders

- package-lock.json
- package.json
- src/components/core/modal/add.tsx
> added headless ui dialog

- src/components/core/data-table/_components/toolbar.tsx
- src/components/core/form/form-dynamic-fields/_components/default.tsx
- src/components/core/form/form-dynamic-fields/types.ts
- src/components/core/form/join-input-unit.tsx
- src/components/core/form/types.ts
- src/components/core/modal/types.ts
- src/components/ui/date-time.tsx
- src/pages/procurement/capital/config/columns/index.tsx
- src/pages/procurement/item-work-order/config/columns/index.tsx
- src/pages/procurement/item-work-order/config/schema/index.ts
- src/pages/procurement/item-work-order/entry.tsx
- src/pages/procurement/item-work-order/useGenerateFieldDefs.tsx
- src/pages/procurement/item/config/columns/index.tsx
- src/pages/procurement/item/details.tsx
- src/pages/procurement/purchaseCostCenter/add-or-update.tsx
- src/pages/procurement/purchaseCostCenter/config/schema/index.ts
- src/pages/procurement/requisition/config/columns/index.tsx
- src/pages/procurement/requisition/provided.tsx
- src/pages/procurement/requisition/useGenerateFieldDefs.tsx
- src/pages/procurement/service/config/columns/index.tsx
- src/pages/procurement/subcategory/config/schema/index.ts
- src/pages/procurement/vendor/config/columns/index.tsx
- src/pages/procurement/vendor/details.tsx
Introduce new props for conditional rendering in toolbar and form components. Refactor schema to remove unused fields and update date handling to allow null values. Clean up console logs and ensure entry updates complete before invalidating queries.
> Enhance toolbar and form components with new props and null handling

- package.json
- src/pages/procurement/log/config/columns/index.tsx
- src/pages/procurement/purchaseCostCenter/index.tsx
Corrected the deployment script and updated accessor keys for item work order and requisition columns to resolve issues on the log and purchase cost page. Added a new icon import for improved UI.
> Fix log and purchase cost page bug

- src/components/pdf/general-statement/index.tsx
- src/components/pdf/general-statement/utils.tsx
- src/components/pdf/item-requstion/index.tsx
- src/components/pdf/item-requstion/utils.tsx
Adjustments made to the PDF generation logic ensure proper footer height and formatting, enhancing the overall layout of requisition documents.
> Fix PDF generation for requisition documents

- src/pages/procurement/requisition/entry.tsx
Adjust conditional rendering for the 'New Item Requisition' section and prevent adding new items when a requisition is received.
> Fix requisition item addition logic and rendering

- src/pages/procurement/capital/config/columns/columns.type.ts
- src/pages/procurement/capital/config/columns/index.tsx
- src/pages/procurement/capital/config/schema/index.ts
- src/pages/procurement/capital/details/information.tsx
- src/pages/procurement/capital/entry.tsx
- src/pages/procurement/capital/useGenerateFieldDefs.tsx
- src/pages/procurement/item/config/query/index.ts
Introduce status and value fields in the capital data structure and update the details modal to reflect these changes. Adjust the display logic to incorporate badges for status representation.
> Add status and value fields to capital details

- src/pages/portfolio/department-teacher/add-or-update/_config/schema/index.ts
- src/pages/portfolio/department-teacher/add-or-update/card/add-or-update.tsx
- src/pages/portfolio/department-teacher/add-or-update/card/index.tsx
- src/pages/portfolio/department-teacher/add-or-update/container.tsx
- src/pages/portfolio/department-teacher/add-or-update/header.tsx
- src/pages/portfolio/department-teacher/add-or-update/index.tsx
- src/pages/portfolio/department-teacher/add-or-update/types.ts
- src/pages/portfolio/department-teacher/index.tsx
- src/routes/private/portfollo.tsx
Introduce a new teachers page along with dynamic field components and validation schemas. This update enhances the portfolio section by allowing management of department teachers, including add and update functionalities.
> Add new teachers page and related components

- src/pages/hr/_config/columns/index.tsx
Modify the department column to display both department and designation names in a combined format.
> Update department column to show combined names

- src/routes/private/portfollo.tsx
Commented out the Teachers route in the portfolio for potential future review and adjustments.
> Comment out Teachers route for future review

- src/pages/portfolio/_config/columns/index.tsx
- src/pages/portfolio/teacher/add-or-update.tsx
> added resign date to teachers table

- src/pages/procurement/category/index.tsx
- src/pages/procurement/internal-cost-center/index.tsx
- src/pages/procurement/item/config/columns/index.tsx
- src/pages/procurement/item/entry.tsx
- src/pages/procurement/purchaseCostCenter/add-or-update.tsx
- src/pages/procurement/purchaseCostCenter/index.tsx
- src/pages/procurement/service/entry.tsx
- src/pages/procurement/subcategory/index.tsx
- src/routes/private/procurement.tsx
> Refactor: Item Requisition and PDF Static swap

- src/components/core/form/switch.tsx
- src/pages/procurement/log/item-work-order-entry/index.tsx
- src/pages/procurement/procure/config/columns/columns.type.ts
- src/pages/procurement/procure/config/query/index.ts
- src/pages/procurement/procure/config/query/queryKeys.ts
- src/pages/procurement/procure/config/schema/index.ts
- src/pages/procurement/procure/entry.tsx
- src/pages/procurement/procure/useGenerateItemWorkOrder.tsx
Introduce a new entry for items in the procurement process and address some minor bugs to enhance functionality.
> Add new items entry and fix minor issues

- src/components/core/form/date-picker.tsx
> fixed date-picker default current date

- src/pages/procurement/category/add-or-update.tsx
- src/pages/procurement/internal-cost-center/add-or-update.tsx
- src/pages/procurement/internal-cost-center/index.tsx
- src/pages/procurement/procure/config/columns/index.tsx
- src/pages/procurement/purchaseCostCenter/add-or-update.tsx
- src/pages/procurement/purchaseCostCenter/config/columns/index.tsx
- src/pages/procurement/service/config/columns/index.tsx
- src/pages/procurement/service/details/index.tsx
- src/pages/procurement/service/entry.tsx
- src/pages/procurement/subcategory/add-or-update.tsx
- src/routes/private/procurement.tsx
- src/utils/validators.ts
> fix: Some bug fixed

- src/pages/portfolio/teacher/index.tsx
> fix:facluty members routes accesse page fixed

- package-lock.json
- src/types/enum.ts
> feat:course offer enum added in type routine(Programs/Doc Upload

- src/pages/portfolio/_config/columns/index.tsx
> feat: Notice url directed conditionally in routine(programs/Doc upload)

- src/components/core/form/index.tsx
- src/components/core/form/otp.tsx
- src/components/core/form/phone.tsx
- src/components/core/form/types.ts
- src/components/ui/input-otp.tsx
- src/pages/hr/user/add-or-update.tsx
- src/pages/portfolio/admission/online-form/add-or-update/personal-information.tsx
- src/pages/portfolio/authorities/add-or-update.tsx
- src/pages/procurement/vendor/add-or-update.tsx
- src/pages/profile/add-or-update.tsx
> added otp form component

- src/components/core/form/form-dynamic-fields/_components/default.tsx
- src/pages/portfolio/useful-links/news/entry.tsx
> style: news and events content and description make RichText Editor

- src/components/core/form/form-dynamic-fields/_components/default.tsx
- src/components/core/form/form-dynamic-fields/types.ts
- src/pages/procurement/procure/config/schema/index.ts
- src/pages/procurement/procure/entry.tsx
- src/pages/procurement/procure/useGenerateGeneralNotes.tsx
- src/pages/procurement/requisition/entry.tsx
> fix: procure file added 

- src/pages/procurement/procure/config/schema/index.ts
- src/pages/procurement/procure/entry.tsx
Addressed issues related to procure form handling, including setting default values and removing null fields from form data. Enhanced validation for quotation entries to ensure minimum requirements are met.
> Fix procure bugs and improve form handling

- src/pages/inquiry/visitor/add-or-update.tsx
- src/pages/portfolio/admission/online-form/add-or-update/bachelor-degree.tsx
- src/pages/portfolio/admission/online-form/add-or-update/header.tsx
- src/pages/portfolio/admission/online-form/add-or-update/personal-information.tsx
> fix: bug fixed

- src/pages/procurement/service/config/columns/index.tsx
- src/pages/procurement/service/details/information.tsx
- src/pages/procurement/service/entry.tsx
> fix:Cost per service change to Cost/service

- package-lock.json
- package.json
- src/components/core/form/date-picker.tsx
- src/components/core/form/index.tsx
- src/components/core/form/radio.tsx
- src/components/core/form/react-select.tsx
- src/components/core/form/types.ts
- src/components/ui/radio-group.tsx
- src/pages/portfolio/admission/online-form/add-or-update/header.tsx
- src/pages/procurement/service/entry.tsx
> fixed date picker issue and added radio component

- src/pages/inquiry/_config/query/index.ts
- src/pages/inquiry/_config/query/queryKeys.ts
- src/pages/inquiry/contact-us/index.tsx
- src/pages/inquiry/contact-us/utils.ts
- src/pages/procurement/procure/config/schema/index.ts
- src/pages/procurement/procure/entry.tsx
- src/pages/procurement/procure/useGenerateFieldDefs.tsx
Introduce a new field for uploading quotation files in the entry form and update the schema to handle this file input. Adjust the data handling to ensure proper submission of the quotation file along with other entry details.
> Add quotation file support in entries

- src/components/core/form/types.ts
> fix: type error fixed in different component

- src/components/pdf/application-form/index.tsx
- src/pages/portfolio/admission/_config/columns/columns.type.ts
- src/pages/portfolio/admission/_config/schema/index.ts
- src/pages/portfolio/admission/online-form/add-or-update/header.tsx
- src/pages/portfolio/admission/online-form/add-or-update/index.tsx
- src/pages/portfolio/admission/online-form/details/information.tsx
> fix: admission form fixed pdf fixed done 

- src/components/pdf/application-form/index.tsx
- src/pages/portfolio/admission/_config/columns/columns.type.ts
- src/pages/portfolio/admission/_config/schema/index.ts
- src/pages/portfolio/admission/online-form/add-or-update/header.tsx
- src/pages/portfolio/admission/online-form/add-or-update/index.tsx
- src/pages/portfolio/admission/online-form/add-or-update/personal-information.tsx
> fix: admission form fixed

- src/pages/procurement/procure/details/index.tsx
- src/pages/procurement/procure/entry.tsx
- src/pages/procurement/procure/index.tsx
- src/pages/procurement/procure/useGenerateItemWorkOrder.tsx
- src/routes/private/procurement.tsx
Remove the item segment and its related conditions, updating navigation paths and component names to reflect the changes for capital procurement. Adjust the document title and ensure proper routing for create, update, and details views.
> Refactor procurement routes and components for capital items

- src/components/core/form/index.tsx
- src/components/core/form/student-id-box.tsx
- src/pages/fde/config/columns/columns.type.ts
- src/pages/fde/config/columns/index.tsx
- src/pages/fde/config/query/index.ts
- src/pages/fde/config/query/queryKeys.ts
- src/pages/fde/form/entry.tsx
- src/pages/fde/list/index.tsx
- src/pages/lib/config/query/index.ts
- src/pages/lib/config/query/queryKeys.ts
- src/pages/lib/course/entry.tsx
- src/pages/lib/course/useGenerateFieldDefs.tsx
- src/pages/public/ban.tsx
> fix: FDE bug fixed

- .env
- src/pages/fde/config/columns/index.tsx
- src/pages/lib/course-assign/useGenerateFieldDefs.tsx
- src/pages/procurement/bill/add-or-update/index.tsx
- src/pages/procurement/bill/add-or-update/useGenerateFieldDefs.tsx
- src/pages/procurement/bill/config/schema/index.ts
- src/pages/procurement/item-request/index.tsx
- src/pages/procurement/log/config/query/index.ts
- src/pages/procurement/log/config/query/queryKeys.ts
- src/pages/procurement/procure(store)/entry.tsx
- src/pages/procurement/procure(store)/useGenerateItemWorkOrder.tsx
Introduce payment method and date fields in the procurement module, along with the ability to filter item requests by status. Update relevant components and schemas to accommodate these enhancements.
> Enhance procurement module with payment details and status filtering

- src/pages/portfolio/admission/online-form/add-or-update/personal-information.tsx
Reorganize the phone number fields in the Personal Information form for better layout and usability. The changes enhance the structure by grouping related fields together.
> Refactor phone number fields in Personal Information form

- src/components/core/form/file-upload/index.tsx
- src/components/core/form/file-upload/previews/image.tsx
- src/components/core/form/types.ts
- src/pages/hr/user/add-or-update.tsx
- src/pages/portfolio/department-teacher/add-or-update/card/index.tsx
- src/pages/portfolio/feature/add-or-update.tsx
- tailwind.config.js
Introduce support for preview classes in the file upload component and enhance procurement forms with better error logging, optional fields, and automatic calculations. Refactor components for improved usability and readability, while adding new reporting features and optimizing existing code.
> Enhance file upload and procurement forms with improved validation and reporting

- src/pages/portfolio/admission/_config/schema/index.ts
- src/pages/procurement/requisition/config/query/index.ts
- src/pages/procurement/requisition/config/query/queryKeys.ts
- src/pages/procurement/requisition/entry.tsx
- src/pages/procurement/requisition/index.tsx
Introduce status filtering for requisitions and update the PORTFOLIO_ADMISSION_SCHEMA to include Barisal while adjusting student ID validation to 9 digits.
> Enhance requisition functionality and update admission schema

- src/components/pdf/application-form/index.tsx
- src/pages/procurement/procure(store)/entry.tsx
- src/pages/procurement/procure/config/query/index.ts
- src/pages/procurement/procure/config/query/queryKeys.ts
- src/pages/procurement/procure/entry.tsx
- src/pages/procurement/procure/index.tsx
Improve the layout of the Entry component by adding a Quotation label and adjusting the grid structure. Enhance procurement queries with optional parameters and introduce a capital summary functionality.
> Update Entry layout and enhance procurement queries

- src/components/core/form/form-dynamic-fields/_components/default.tsx
- src/components/core/form/form-dynamic-fields/types.ts
- src/pages/procurement/procure(store)/useGenerateItemWorkOrder.tsx
Enhance the DefaultDynamicFields component to accommodate dynamic column widths by introducing minWidth and maxWidth properties. Update the FieldDef type accordingly.
> Support dynamic column widths in DefaultDynamicFields component

- src/lib/common-queries/other/index.ts
- src/lib/common-queries/other/query-keys.ts
- src/pages/fde/report/config/columns/columns.type.ts
- src/pages/fde/report/config/columns/facetedFilters.tsx
- src/pages/fde/report/config/columns/index.tsx
- src/pages/fde/report/config/query/index.ts
- src/pages/fde/report/config/query/queryKeys.ts
- src/pages/fde/report/config/schema/index.ts
- src/pages/fde/report/config/types/index.tsx
- src/pages/fde/report/teacher-grade/index.tsx
- src/pages/lib/config/schema/index.ts
- src/pages/lib/room-allocation/entry-3/_components/allocation-summary.tsx
- src/pages/lib/room-allocation/entry-3/_components/assignment-dialog.tsx
- src/pages/lib/room-allocation/entry-3/_components/delete-allocation-dialog.tsx
- src/pages/lib/room-allocation/entry-3/hooks/use-room-allocation.ts
- src/pages/lib/room-allocation/entry-3/index.tsx
- src/pages/lib/room-allocation/entry-3/lib/types.ts
- src/pages/lib/room-allocation/entry/index.tsx
- src/routes/private/lib.tsx
> feat: Room Allocation api added

- src/pages/lib/config/query/index.ts
- src/pages/lib/config/query/queryKeys.ts
- src/pages/lib/room-allocation/entry-3/_components/allocation-summary.tsx
- src/pages/lib/room-allocation/entry-3/_components/assignment-dialog.tsx
- src/pages/lib/room-allocation/entry-3/_components/time-range-picker.tsx
- src/pages/lib/room-allocation/entry-3/hooks/use-room-allocation.ts
- src/pages/lib/room-allocation/entry-3/index.tsx
- src/pages/lib/room-allocation/entry-3/lib/time-utils.ts
- src/pages/lib/room-allocation/entry-3/lib/types.ts
> fix: InvalidQuery Problem sloved in Room allocation

- src/components/pdf/room-allocation-teacher-wise/converted-data.ts
- src/components/pdf/room-allocation-teacher-wise/index.tsx
- src/components/pdf/room-allocation-teacher-wise/utils.tsx
- src/lib/common-queries/other/index.ts
- src/lib/common-queries/other/query-keys.ts
- src/pages/lib/config/columns/index.tsx
- src/pages/lib/config/schema/index.ts
- src/pages/lib/room-allocation/entry-1/_config/hooks.ts
- src/pages/lib/room-allocation/entry-3/_components/allocation-summary.tsx
- src/pages/lib/room-allocation/entry-3/_components/assignment-dialog.tsx
- src/pages/lib/room-allocation/entry-3/_components/time-range-picker.tsx
- src/pages/lib/room-allocation/entry-3/index.tsx
- src/pages/lib/room-allocation/entry-3/teachers-wise-room-allocation.tsx
- src/pages/lib/room/add-or-update.tsx
> Teacher individual room allocation added 

- src/components/pdf/room-allocation/converted-data.ts
- src/components/pdf/room-allocation/index.tsx
- src/pages/lib/course-assign/useGenerateFieldDefs.tsx
> fix : Eub fix done

- src/lib/common-queries/other/index.ts
- src/pages/fde/form/index.tsx
- src/pages/hr/auth/add-or-update.tsx
- src/pages/hr/auth/page-assign.tsx
- src/pages/lib/config/columns/index.tsx
- src/pages/lib/course/index.tsx
- src/pages/lib/room-allocation/entry-3/_components/time-range-picker.tsx
- src/pages/lib/room/index.tsx
- src/pages/lib/semester/index.tsx
- src/routes/private/fde.tsx
- src/routes/private/index.tsx
- src/routes/private/lib.tsx
- src/routes/private/profile.tsx
- src/types/index.ts
- src/utils/routes/filter/routes.ts
Update routing and related page information to reflect the change from 'Form' to 'Submission'.
> Rename 'Form' to 'Submission' in routing and page info updates

- src/components/pdf/fde-qr-code/index.tsx
- src/pages/lib/config/columns/index.tsx
- src/pages/lib/config/schema/index.ts
- src/pages/lib/course-assign/entry.tsx
- src/pages/lib/course-assign/useGenerateFieldDefs.tsx
- src/pages/lib/course/entry.tsx
- src/pages/lib/course/useGenerateFieldDefs.tsx
Remove 'shift_type' and 'regular/evening' sections, consolidating them into a single 'course_section' for improved clarity and maintainability. Adjust related form handling and schema accordingly.
> Refactor course section handling

- package-lock.json
- package.json
- src/pages/lib/course-assign/side-search.tsx
Introduce match-sorter and use-debounce to improve the course search experience by optimizing filtering and reducing unnecessary renders.
> Enhance course search functionality with match-sorter and use-debounce

- src/components/pdf/fde-qr-bulk/index.tsx
- src/components/pdf/fde-qr-bulk/utils.tsx
- src/components/pdf/fde-qr-code/index.tsx
- src/components/pdf/fde-qr-code/utils.tsx
- src/lib/common-queries/other/index.ts
- src/pages/fde/bulk-qr/index.tsx
- src/pages/fde/bulk-qr/utils.tsx
- src/pages/fde/config/columns/index.tsx
- src/pages/fde/form/info.tsx
- src/routes/private/fde.tsx
Introduce a new Bulk QR page to enhance the functionality of the application, allowing users to generate QR codes for course evaluations. This update includes adjustments to the layout, data handling, and integration of department selection.
> Add Bulk QR page
